import * as cdk from 'aws-cdk-lib';
import { Validations } from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import * as ssm from 'aws-cdk-lib/aws-ssm';
import { Construct } from 'constructs';
import { DATABASE_NAME, DATABASE_USERNAME, POSTGRES_VERSION, ResourceNames } from './config';

export interface DataStackProps extends cdk.StackProps {
  readonly vpc: ec2.IVpc;
  readonly names: ResourceNames;
}

/**
 * RDS PostgreSQL 15, plus the security group that grants access to it.
 *
 * The instance lives in the isolated subnets, which have no route off the VPC in
 * either direction. Reaching it requires being inside the VPC *and* carrying the
 * client security group this stack publishes.
 */
export class DataStack extends cdk.Stack {
  public readonly instance: rds.DatabaseInstance;

  /** Generated credentials. Consumers are granted read access, never the value. */
  public readonly secret: secretsmanager.ISecret;

  /**
   * Attach this to anything that needs to talk to the database — the Fargate
   * service and the migration Lambda both do.
   *
   * Access is modelled as "hold this group" rather than "come from this CIDR",
   * and the group is defined here rather than in the consuming stacks. If RDS
   * had to reference the Fargate service's own security group, DataStack would
   * depend on AppStack while AppStack depends on DataStack for the endpoint — a
   * cycle CloudFormation cannot deploy. Owning the client group on the database
   * side breaks it, and keeps the list of who can reach the database readable
   * from one place.
   */
  public readonly clientSecurityGroup: ec2.SecurityGroup;

  /**
   * The database's own security group.
   *
   * Exposed so that AppStack can add its Fargate service as an allowed source
   * directly. The service cannot simply wear `clientSecurityGroup` instead:
   * attaching a DataStack security group to a load-balancer target makes CDK add
   * the ALB's ingress rules to that group, which points DataStack at AppStack and
   * produces a dependency cycle. Adding the rule from the AppStack side keeps the
   * dependency one-way.
   */
  public readonly databaseSecurityGroup: ec2.SecurityGroup;

  constructor(scope: Construct, id: string, props: DataStackProps) {
    super(scope, id, props);

    const { vpc, names } = props;

    this.clientSecurityGroup = new ec2.SecurityGroup(this, 'DbClientSecurityGroup', {
      vpc,
      securityGroupName: names.dbClientSecurityGroup,
      description: 'Grants its holder access to the PointHub database',
      allowAllOutbound: true,
    });

    this.databaseSecurityGroup = new ec2.SecurityGroup(this, 'DbSecurityGroup', {
      vpc,
      securityGroupName: names.dbSecurityGroup,
      description: 'PointHub RDS PostgreSQL',
      // The database initiates nothing.
      allowAllOutbound: false,
    });

    this.databaseSecurityGroup.addIngressRule(
      this.clientSecurityGroup,
      ec2.Port.tcp(5432),
      'PostgreSQL from holders of the db-client group'
    );

    // -----------------------------------------------------------------------
    // Credentials
    // -----------------------------------------------------------------------
    // Generated by Secrets Manager and never rendered into the template, a
    // parameter or a task definition. The password does not exist in this
    // repository or in CloudFormation at any point.
    const credentials = rds.Credentials.fromGeneratedSecret(DATABASE_USERNAME, {
      secretName: names.dbSecret,
      excludeCharacters: ' %+~`#$&*()|[]{}:;<>?!\'/@"\\',
    });

    // -----------------------------------------------------------------------
    // Parameter group
    // -----------------------------------------------------------------------
    const parameterGroup = new rds.ParameterGroup(this, 'ParameterGroup', {
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.of(POSTGRES_VERSION, '15'),
      }),
      // ASCII only. RDS rejects a parameter group description containing
      // non-printable or non-ASCII characters with InvalidRequest, and an em
      // dash here is enough to fail the whole stack create.
      description: 'PointHub PostgreSQL 15 - TLS required',
      parameters: {
        // Reject any non-TLS connection at the server. This is the setting that
        // makes the DB_SSL/DB_CA_PATH handling in src/db/pool.ts load-bearing
        // rather than decorative: with force_ssl on, a client that skips TLS
        // fails to connect at all instead of quietly sending credentials in
        // clear text.
        'rds.force_ssl': '1',

        // Log statements that take longer than a second. The earn endpoint has a
        // p95 budget of 150 ms, so anything at this threshold is a real problem
        // worth having a record of.
        log_min_duration_statement: '1000',
      },
    });

    // -----------------------------------------------------------------------
    // Instance
    // -----------------------------------------------------------------------
    this.instance = new rds.DatabaseInstance(this, 'Instance', {
      instanceIdentifier: names.dbInstance,
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.of(POSTGRES_VERSION, '15'),
      }),
      instanceType: ec2.InstanceType.of(
        ec2.InstanceClass.BURSTABLE4_GRAVITON,
        ec2.InstanceSize.MICRO
      ),

      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [this.databaseSecurityGroup],

      // No public endpoint. Combined with isolated subnets this is belt and
      // braces, and deliberately so.
      publiclyAccessible: false,

      credentials,
      databaseName: DATABASE_NAME,
      parameterGroup,

      allocatedStorage: 20,
      maxAllocatedStorage: 50, // storage autoscaling headroom, no upfront cost
      storageType: rds.StorageType.GP3,
      storageEncrypted: true, // AWS-managed key; the ledger is financial data

      backupRetention: cdk.Duration.days(7),
      preferredBackupWindow: '18:00-19:00', // 01:00-02:00 Asia/Bangkok
      preferredMaintenanceWindow: 'Sun:19:00-Sun:20:00', // Mon 02:00-03:00 Asia/Bangkok
      deleteAutomatedBackups: true,

      // Multi-AZ is off. This is a workshop environment on a burstable instance;
      // the standby would roughly double the largest line on the bill for
      // availability nothing here measures. Production loyalty data would want
      // it on.
      multiAz: false,

      // Send PostgreSQL logs to CloudWatch so a failed migration or a slow query
      // is inspectable without connecting to the instance.
      //
      // Retention is set by declaring the destination log groups below rather
      // than by passing `cloudwatchLogsRetention`. That property makes CDK
      // synthesise a LogRetention custom resource — a Lambda plus an IAM role
      // carrying AWSLambdaBasicExecutionRole and a wildcard resource — which
      // trips AwsSolutions-IAM4 and IAM5 on a construct this stack does not own.
      // Those two findings also cannot be acknowledged in cdk-nag 3.0.2: the
      // finding id it prints, `AwsSolutions-IAM4[Policy::arn:...]`, is rejected
      // by the validator because the `::` inside the bracket collides with the
      // `prefix::RuleName` delimiter, and bare-rule-id acknowledgement does not
      // match granular findings. Declaring the log groups avoids the custom
      // resource altogether, which is both cleaner and one less moving part.
      cloudwatchLogsExports: ['postgresql', 'upgrade'],

      // Workshop account: this must be destroyable in one command. Both of these
      // are wrong for a real production database and are called out in
      // infra/README.md.
      deletionProtection: false,
      removalPolicy: cdk.RemovalPolicy.DESTROY,

      // Minor versions are applied in the maintenance window rather than never.
      autoMinorVersionUpgrade: true,
      enablePerformanceInsights: false, // chargeable beyond 7 days retention
    });

    // -----------------------------------------------------------------------
    // Log groups for the exported PostgreSQL logs
    // -----------------------------------------------------------------------
    // RDS writes to these fixed names, derived from the instance identifier. By
    // declaring them here they are created with a retention policy and are torn
    // down with the stack, instead of being auto-created by RDS with no
    // expiry and then surviving `cdk destroy`.
    // The dependency direction matters and is the opposite of what reading the
    // code suggests. RDS creates these groups itself the first time it exports a
    // log line, and a group RDS created is not owned by CloudFormation — so if
    // the instance comes up first, this resource fails with AlreadyExists and
    // takes the stack down with it. Declaring the instance dependent on the
    // groups forces them to exist first, after which RDS simply writes into
    // them.
    //
    // Worth knowing when recovering from a failed deploy: because RDS owns any
    // group it auto-created, a rollback leaves it behind, and the next attempt
    // hits AlreadyExists until it is deleted by hand.
    for (const logType of ['postgresql', 'upgrade']) {
      const logGroup = new cdk.aws_logs.LogGroup(this, `DbLogGroup${logType}`, {
        logGroupName: `/aws/rds/instance/${names.dbInstance}/${logType}`,
        retention: cdk.aws_logs.RetentionDays.TWO_WEEKS,
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });

      this.instance.node.addDependency(logGroup);
    }

    // -----------------------------------------------------------------------
    // Cross-stack values
    // -----------------------------------------------------------------------
    const secret = this.instance.secret as secretsmanager.ISecret;
    this.secret = secret;

    new ssm.StringParameter(this, 'DbHostParameter', {
      parameterName: names.ssm.dbHost,
      stringValue: this.instance.dbInstanceEndpointAddress,
      description: 'PointHub RDS endpoint address',
    });

    new ssm.StringParameter(this, 'DbPortParameter', {
      parameterName: names.ssm.dbPort,
      stringValue: this.instance.dbInstanceEndpointPort,
      description: 'PointHub RDS endpoint port',
    });

    new ssm.StringParameter(this, 'DbNameParameter', {
      parameterName: names.ssm.dbName,
      stringValue: DATABASE_NAME,
      description: 'PointHub database name',
    });

    // The ARN, not the value. Consumers read the secret at runtime through IAM.
    new ssm.StringParameter(this, 'DbSecretArnParameter', {
      parameterName: names.ssm.dbSecretArn,
      stringValue: secret.secretArn,
      description: 'ARN of the Secrets Manager secret holding the DB credentials',
    });

    new ssm.StringParameter(this, 'DbClientSecurityGroupParameter', {
      parameterName: names.ssm.dbClientSecurityGroupId,
      stringValue: this.clientSecurityGroup.securityGroupId,
      description: 'Security group granting access to the PointHub database',
    });

    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.instance.dbInstanceEndpointAddress,
    });

    new cdk.CfnOutput(this, 'DbSecretName', {
      value: secret.secretName,
      description: 'Read with: aws secretsmanager get-secret-value --secret-id <name>',
    });

    this.acknowledgeAcceptedRisks(secret);
  }

  /**
   * cdk-nag findings that are accepted rather than fixed.
   *
   * Synthesis fails on any unacknowledged finding, so each entry below is a
   * decision someone has to justify, not a checkbox. Nothing here is
   * acknowledged because it was inconvenient to fix — the four RDS/Secrets
   * items are deliberate trade-offs recorded in infra/README.md, and the two
   * IAM items are on a construct CDK owns.
   */
  private acknowledgeAcceptedRisks(secret: secretsmanager.ISecret): void {
    Validations.of(secret).acknowledge({
      id: 'AwsSolutions::AwsSolutions-SMG4',
      reason:
        'Automatic rotation is deliberately not scheduled. The task reads DB_PASSWORD ' +
        'once at process start, injected by ECS from this secret, and pg holds pooled ' +
        'connections for the life of the process. Single-user rotation would change the ' +
        'password underneath running tasks and break every connection until the service ' +
        'was redeployed — a scheduled monthly outage traded for a rotation nobody is ' +
        'consuming. Enabling it correctly requires src/db/pool.ts to fetch credentials ' +
        'at connect time rather than read an environment variable; that is a code change ' +
        'outside this deployment work and is recorded as a limitation in infra/README.md.',
    });

    Validations.of(this.instance).acknowledge({
      id: 'AwsSolutions::AwsSolutions-RDS3',
      reason:
        'Multi-AZ is off. The standby doubles the largest recurring line on the bill for ' +
        'a failover objective this workshop environment does not measure, and it is a ' +
        'one-flag change if that objective ever appears. Durability is covered separately ' +
        'by 7 days of automated backups. A production loyalty ledger should enable it.',
    });

    Validations.of(this.instance).acknowledge({
      id: 'AwsSolutions::AwsSolutions-RDS10',
      reason:
        'Deletion protection is off because `npm run destroy` has to be able to remove ' +
        'this instance in one command — the account is a shared workshop account and ' +
        'leaving billable resources behind is the more likely failure than an accidental ' +
        'delete. This is the wrong setting for a real production database.',
    });

    Validations.of(this.instance).acknowledge({
      id: 'AwsSolutions::AwsSolutions-RDS11',
      reason:
        'The default port 5432 is kept. Port obfuscation raises the cost of untargeted ' +
        'scanning, and there is no scanner that can reach this instance: it sits in ' +
        'isolated subnets with no route to or from the internet, is not publicly ' +
        'accessible, and only accepts traffic from holders of the pointhub-db-client ' +
        'security group. Moving the port would add a value to keep in sync across the ' +
        'container, the migration Lambda and local development in exchange for no ' +
        'reachable attack surface.',
    });
  }
}
